version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.9.8
    networks:
      - monitoring
    ports:
      - "3100:3100"
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
      - /tmp/loki/index:/loki/index
      - /tmp/loki/chunks:/loki/chunks
      - /tmp/loki/index_cache:/loki/index_cache
      - /tmp/loki/wal:/loki/wal
      - /tmp/loki/compactor:/loki/compactor
    user: "10001:10001"

  tempo:
    image: grafana/tempo:latest
    networks:
      - monitoring
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4321:4321"

  nginx:
    image: nginx:latest
    networks:
      - monitoring
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  application:
    image: nginxdemos/hello
    networks:
      - monitoring
    ports:
      - "8080:80"

  mimir:
    image: grafana/mimir:latest
    networks:
      - monitoring
    ports:
      - "9009:9009"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ./mimir.yml:/etc/mimir/mimir.yml

networks:
  monitoring:
    driver: bridge
