global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'application'
    static_configs:
      - targets: ['application:8080']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
  - job_name: 'mimir'
    static_configs:
      - targets: ['mimir:9009']
